/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rptis.obo.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 * @author elmonazareno
 */
@Template(OKCancelPage.class)
public class BuildingFaasCreateOptionPage extends javax.swing.JPanel {

    /**
     * Creates new form BuildingFassCreateOption
     */
    public BuildingFaasCreateOptionPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        xRadio2 = new com.rameses.rcp.control.XRadio();

        xLabel1.setExpression("Please select an option for the FAAS");
        xLabel1.setShowCaption(false);
        xFormPanel1.add(xLabel1);

        xRadio1.setCellPadding(new java.awt.Insets(10, 20, 0, 0));
        xRadio1.setShowCaption(false);
        xRadio1.setText("Create New Building FAAS");
        xRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio1ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xRadio1);

        xRadio3.setCellPadding(new java.awt.Insets(10, 20, 0, 0));
        xRadio3.setShowCaption(false);
        xRadio3.setText("Create New Machinery FAAS");
        xRadio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio3ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xRadio3);

        xRadio2.setCellPadding(new java.awt.Insets(10, 20, 0, 0));
        xRadio2.setShowCaption(false);
        xRadio2.setText("Link Existing FAAS");
        xRadio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio2ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xRadio2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio1ActionPerformed

    private void xRadio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio2ActionPerformed

    private void xRadio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    private com.rameses.rcp.control.XRadio xRadio3;
    // End of variables declaration//GEN-END:variables
}
